# Hypothisis Testing 1

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

In [2]:
df=pd.read_csv('Cutlets.csv')
df.head()

UnitA   UnitB
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
stats.ttest_ind(df.UnitA,df.UnitB)

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

# Hypothesis Testing 2

In [4]:
dt=pd.read_csv('LabTAT.csv')
dt.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [5]:
dt.iloc[0:3].mean()

Laboratory 1    182.870000
Laboratory 2    182.120000
Laboratory 3    192.126667
Laboratory 4    170.700000
dtype: float64

In [6]:
stats.f_oneway(dt.iloc[:,0],dt.iloc[:,1],dt.iloc[:,2],dt.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

# Hypothesis testing 3

In [7]:
dt=pd.read_csv('BuyerRatio.csv')
dt

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [8]:
dt1=dt.drop(columns=['Observed Values'])

In [9]:
dt2=np.array(dt1)
dt2

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [10]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64 
 2   West             2 non-null      int64 
 3   North            2 non-null      int64 
 4   South            2 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes


In [11]:
chi2_contingency(dt2)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

# Hypothisis testing 4

In [12]:
dt=pd.read_csv('Costomer+OrderForm.csv')

In [13]:
dt.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [14]:
data=dt.apply(pd.value_counts)
data

Phillippines  Indonesia  Malta  India
Error Free           271        267    269    280
Defective             29         33     31     20

In [15]:
stats.chi2_contingency(data)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))